import "./global.css";
import Header from "./components/header/header";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <Header />
        <main>{children}</main>
        <footer>footer</footer>
      </body>
    </html>
  );
}
