import AppFrame from "@components/layout/AppFrame";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body>
        <AppFrame>
          {children}
        </AppFrame>
      </body>
    </html>
  )
}
