import AppFrame from "@components/layout/AppFrame";
import ApolloProviders from "./commons/graphql/ApolloProviders";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body>
        <ApolloProviders>
          <AppFrame>
            {children}
          </AppFrame>
        </ApolloProviders>
      </body>
    </html>
  )
}
