import type { Metadata } from "next";
import "./globals.css";
import ApolloSetting from "../commons/settings/apollo-setting";
import { IsEditProvider } from "@/commons/provider/isEditProvider";
import Layout from "@/commons/layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`root_body`}>
        <ApolloSetting>
          <IsEditProvider>
            <Layout>{children}</Layout>
          </IsEditProvider>
        </ApolloSetting>
      </body>
    </html>
  );
}
