import './globals.css'
import localFont from 'next/font/local'
import { Inter } from 'next/font/google'
import ApolloSetting from 'commons/settings/apollo-setting'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const pretendard = localFont({
  src: './fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
})

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <ApolloSetting>
        <body className={`${pretendard.variable} ${inter.className}`}>{children}</body>
      </ApolloSetting>
    </html>
  )
}
