// src/app/layout.tsx
import "./globals.css";
import ApolloSetting from "@/commons/settings/apollo-setting";
import React from 'react';

export const metadata = {
  title: "My Next.js App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body>
        <ApolloSetting>
          {children} {/* <= Layout 컴포넌트를 제거하고 children을 직접 렌더링 */}
        </ApolloSetting>
      </body>
    </html>
  );
}