import "./globals.css";
import ApolloSetting from "@/commons/settings/apollo-setting";
import Layout from "@/commons/layout";
import React from 'react';

export const metadata = {
  title: "My Next.js App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body>
        <ApolloSetting>
          <Layout>{children}</Layout>
        </ApolloSetting>
      </body>
    </html>
  );
}
