import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ApolloSetting from "./commons/settings/apollo-setting";
import Layout from "./commons/layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface IProps {
  children: React.ReactNode;
}

const globalFont = localFont({
  src: "./fonts/Pretendard-Regular.woff2",
  variable: "--globalFont",
});

export default function RootLayout({ children }: IProps) {
  return (
    <html lang="ko">
      <body className={`${globalFont.variable}`}>
        <ApolloSetting>
          <Layout>{children}</Layout>
        </ApolloSetting>
      </body>
    </html>
  );
}
