import './globals.css';
import ConditionalHeader from '../commons/header/conditional-header';
import { ReactNode } from 'react';
import ApolloSetting from '../providers/apollo-setting';
import { AuthProvider } from '../contexts/AuthContext';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>
        <ApolloSetting>
          <AuthProvider>
            <ConditionalHeader />
            {children}
          </AuthProvider>
        </ApolloSetting>
      </body>
    </html>
  );
}
