
export const tripTalkMockData = [
  {
    id: "1",
    title: "제주 섬이 한낮 찬란할 때가 생각나네요",
    coverImage: "/images/desktop/detail-page-1.png",
    authorName: "웅진동",
    authorProfileImage: "/images/mobile/profile/img-1.png",
    likeCount: 24,
    badCount: 24,
    createdAt: "2024.11.11",
  },
  {
    id: "2",
    title: "길 걷다 잃었던 고잉한테 편지 받았어요",
    coverImage: "/images/mobile/b.png",
    authorName: "강릉동",
    authorProfileImage: "/images/mobile/profile/img-2.png",
    likeCount: 24,
    badCount: 24,
    createdAt: "2024.11.11",
  },
  {
    id: "3",
    title: "경춘 여름보다 보기 좋네요 사랑하고 싶어요!",
    coverImage: "/images/mobile/c.png",
    authorName: "용담동",
    authorProfileImage: "/images/mobile/profile/img-3.png",
    likeCount: 24,
    badCount: 24,
    createdAt: "2024.11.11",
  },
  {
    id: "4",
    title: "누가 왕알 향한다고 했어 나밖에 없는가?",
    coverImage: "/images/mobile/a.png",
    authorName: "중문동",
    authorProfileImage: "/images/mobile/profile/img-4.png",
    likeCount: 24,
    badCount: 24,
    createdAt: "2024.11.11",
  },
];



export const mockRows = [
  { id: 243,
    image: "/images/mobile/a.png",
    title: "제주 섬이 19년차",
    author: "홍길동",
    authorName: "홍길동",
    authorProfileImage: "/images/mobile/profile/img-1.png",
    coverImage: "/images/mobile/a.png",
    likeCount: 24,
    badCount: 24,
    date: "2024.12.16",
    createdAt: "2024.12.16",
  },
  { id: 242,
    image: "/images/mobile/b.png",
    title: "강남 살아 1004일차",
    author: "홍길동",
    authorName: "홍길동",
    authorProfileImage: "/images/mobile/profile/img-2.png",
    coverImage: "/images/mobile/b.png",
    likeCount: 18,
    badCount: 3,
    date: "2024.12.16",
    createdAt: "2024.12.16",
  },
  { id: 241,  
    image: "/images/mobile/c.png",
    title: "길 걷다 잃었는데 고양이한테 선물 받았어요",
    author: "홍길동",
    authorName: "홍길동",
    authorProfileImage: "/images/mobile/profile/img-3.png",
    coverImage: "/images/mobile/c.png",
    likeCount: 32,
    badCount: 1,
    date: "2024.12.16",
    createdAt: "2024.12.16",
  },
  { id: 240,
    image: "/images/mobile/d.png",
    title: "오늘 날씨 너무 좋아서 바다 보러 왔어요~",
    author: "홍길동",
    authorName: "홍길동",
    authorProfileImage: "/images/mobile/profile/img-4.png",
    coverImage: "/images/mobile/d.png",
    likeCount: 45,
    badCount: 2,
    date: "2024.12.16",
    createdAt: "2024.12.16",
  },
  { id: 239,
    image: "/images/mobile/e.png",
    title: "누가 밤만 왕한다 했어! 나밖에 없는데?",
    author: "홍길동",
    authorName: "홍길동",
    authorProfileImage: "/images/mobile/profile/img-1.png",
    coverImage: "/images/mobile/e.png",
    likeCount: 12,
    badCount: 8,
    date: "2024.12.16",
    createdAt: "2024.12.16",
  },
  { id: 238,
    image: "/images/mobile/f.png",
    title: "여행 브이로그 시작기 재밌게 했네요 😊",
    author: "홍길동",
    authorName: "홍길동",
    authorProfileImage: "/images/mobile/profile/img-2.png",
    coverImage: "/images/mobile/f.png",
    likeCount: 67,
    badCount: 0,
    date: "2024.12.16",
    createdAt: "2024.12.16",
  },
  { id: 237,
    image: "/images/mobile/g.png",
    title: "사회부에서 근무 날씨 덕에 밥맛이 꿀맛! 디아몬드해변 어떤 가야하나요",
    author: "홍범준",
    authorName: "홍범준",
    authorProfileImage: "/images/mobile/profile/img-6.png",
    coverImage: "/images/mobile/a.png",
    likeCount: 29,
    badCount: 4,
    date: "2024.12.16",
    createdAt: "2024.12.16",
  },
  { id: 236,
    image: "/images/mobile/h.png",
    title: "아기는 가슴이 여린이라죠 ㅋㅋㅋ",
    author: "문채율",
    authorName: "문채율",
    authorProfileImage: "/images/mobile/profile/img-7.png",
    coverImage: "/images/mobile/b.png",
    likeCount: 15,
    badCount: 12,
    date: "2024.12.16",
    createdAt: "2024.12.16",
  },
  { id: 235,
    image: "/images/mobile/i.png",
    title: "섬마을 바닷바람에 마음은 다독다독 사랑만 남네",
    author: "한서인",
    authorName: "한서인",
    authorProfileImage: "/images/mobile/profile/img-8.png",
    coverImage: "/images/mobile/c.png",
    likeCount: 38,
    badCount: 1,
    date: "2024.12.16",
    createdAt: "2024.12.16",
  },
  { id: 234,
    image: "/images/mobile/j.png",
    title: "경복 아메리카노 보기 힘들다",
    author: "홍길동",
    authorName: "홍길동",
    authorProfileImage: "/images/mobile/profile/img.png",
    coverImage: "/images/mobile/d.png",
    likeCount: 21,
    badCount: 6,
    date: "2024.12.16",
    createdAt: "2024.12.16",
  },
];


// 공지사항 데이터
export const noticeMockData = [
  { id: 301, title: "[공지] 서비스 점검 안내", author: "관리자", date: "2024.12.20" },
  { id: 302, title: "[공지] 새로운 기능 업데이트", author: "관리자", date: "2024.12.19" },
  { id: 303, title: "[공지] 이용약관 변경 안내", author: "관리자", date: "2024.12.18" },
  { id: 304, title: "[공지] 개인정보처리방침 개정", author: "관리자", date: "2024.12.17" },
  { id: 305, title: "[공지] 연말연시 고객센터 운영시간", author: "관리자", date: "2024.12.16" },
];

// 이벤트 데이터
export const eventMockData = [
  { id: 401, title: "🎄 크리스마스 특별 이벤트", author: "이벤트팀", date: "2024.12.20" },
  { id: 402, title: "⭐ 연말 감사 이벤트", author: "이벤트팀", date: "2024.12.19" },
  { id: 403, title: "🎁 신규 회원 가입 이벤트", author: "이벤트팀", date: "2024.12.18" },
  { id: 404, title: "🏆 베스트 리뷰 선정 이벤트", author: "이벤트팀", date: "2024.12.17" },
  { id: 405, title: "💝 추천인 이벤트", author: "이벤트팀", date: "2024.12.16" },
];

// FAQ 데이터
export const faqMockData = [
  { id: 501, title: "예약 취소는 어떻게 하나요?", author: "고객센터", date: "2024.12.15" },
  { id: 502, title: "결제 방법에는 어떤 것들이 있나요?", author: "고객센터", date: "2024.12.14" },
  { id: 503, title: "회원가입은 어떻게 하나요?", author: "고객센터", date: "2024.12.13" },
  { id: 504, title: "비밀번호를 잊어버렸어요", author: "고객센터", date: "2024.12.12" },
  { id: 505, title: "포인트는 어떻게 사용하나요?", author: "고객센터", date: "2024.12.11" },
];

export const mocksData = {
  tripTalkMockData: tripTalkMockData,
  mockRows: mockRows,
  noticeMockData: noticeMockData,
  eventMockData: eventMockData,
  faqMockData: faqMockData,
}
