'use client';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
// import './BoardsNew.css';
import ApolloSetting from '@/commons/providers/apollo-provider';
import Layout from '@/commons/layout';
import { usePathname } from 'next/navigation';
import ApiUploadProvider from '@/commons/providers/apollo-provider';
import ApiHeaderProvider from '@/commons/providers/apollo-provider';
import { useEffect } from 'react';
import { useAccessTokenStore } from '@/commons/stores/access-token-store';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ApiHeaderProvider>
          {pathname === '/boards' ? <Layout>{children}</Layout> : children}
        </ApiHeaderProvider>
      </body>
    </html>
  );
}
