export const hotSectionMock = [
    {
        id: 1,
        writer: "홍길동",
        title: "제주살이 1일차 청산별곡이 생각나네요",
        content: "제주살이 1일차 청산별곡이 생각나네요.",
        image: "/images/hot/hot01.png",
        profileImage: "/images/profile/profile01.png",
        like: 24,
        createdAt: "2024.11.11",
    },
    {
        id: 2,
        writer: "성시경",
        title: "길 걷고 있었는데 고양이한테 간택 받았어요",
        content: "길 걷고 있었는데 고양이한테 간택 받았어요.",
        image: "/images/hot/hot02.png",
        profileImage: "/images/profile/profile02.png",
        like: 24,
        createdAt: "2025.08.19",
    },
    {
        id: 3,
        writer: "홍길동",
        title: "강릉 여름바다 보기좋네요 서핑하고 싶어요!",
        content: "강릉 여름바다 보기좋네요 서핑하고 싶어요!",
        image: "/images/hot/hot03.png",
        profileImage: "/images/profile/profile03.png",
        like: 24,
        createdAt: "2024.11.11",
    },
    {
        id: 4,
        writer: "홍길동",
        title: "누가 양양 핫하다고 했어 나 밖에 없는데?",
        content: "누가 양양 핫하다고 했어 나 밖에 없는데?",
        image: "/images/hot/hot04.png",
        profileImage: "/images/profile/profile04.png",
        like: 24,
        createdAt: "2024.11.11",
    }
];