import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import ApolloSetting from '@/shared/api/apollo/provider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const pretendard = localFont({
  src: './fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
})
interface RootProps {
  children: React.ReactNode
}
export default function RootLayout(props: RootProps) {
  return (
    <html lang="en">
      <body className={`${pretendard.variable} antialiased`}>
        <div className="container">
          <ApolloSetting pages={props.children} />
        </div>
      </body>
    </html>
  )
}
